# This workflow will build a Java project with Maven and then scan with the WhiteSource Unified Agent for effective vulnerabilities.

name: Whitesource Prioritize Java with Maven

on:
  push:
    branches: [ prioritize ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
    - name: WhiteSource Unified Agent Scan
      env:
        APIKEY: ${{secrets.APIKEY}}
      run: |
        curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
        echo UA downloaded successfully
        export WS_ENABLEIMPACTANALYSIS=true
        export WS_REQUIREKNOWNSHA1=false
        export WS_RESOLVEALLDEPENDENCIES=false
        export WS_MAVEN_RESOLVEDEPENDENCIES=true
        export WS_MAVEN_AGGREGATEMODULES=true
        java -jar wss-unified-agent.jar -appPath ./target/owaspSecurityShepherd.war -d ./ -apikey $APIKEY -product GH_${{ github.event.repository.name }} -project ${{ github.ref }}_Prioritize