# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - xyzzy

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  WS_APIKEY: "d655369afcaa4bedbafed8aeab0b189b972e1e8a1bfa4ead8a4a39e97959b7fe"
  WS_PROJECTNAME: "aspnetcore-realworld-example-app-UA5"
  WS_RESOLVEALLDEPENDENCIES: "false"
  WS_ENABLEIMPACTANALYSIS: "true"
  WS_REQUIREKNOWNSHA1: "false"
  WS_NUGET_RUNPRESTEP: "true"
  WS_NUGET_RESTOREDEPENDENCIES: "true"
  WS_NUGET_RESOLVEDEPENDENCIES: "true"
  WS_NUGET_RESOLVEPACKAGECONFIGFILES: "true"
  WS_NUGET_RESOLVENUSPECFILES: "true"
  WS_NUGET_RESOLVECSPROJFILES: "true"
  WS_NUGET_RESOLVEASSETSFILES: "true"
  WS_NUGET_IGNORESOURCEFILES: "true"

steps:
- checkout: none

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git clone https://github.com/hugh-whitesource/aspnetcore-realworld-example-app.git
      cd aspnetcore-realworld-example-app
      git checkout 93ed4ba61b600509b62ace9cf57d3c7ccb9f2c96

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'

- task: PowerShell@2
  displayName: 'Download latest agent'
  inputs:
    targetType: 'inline'
    script: 'Start-BitsTransfer -Source https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar -Destination wss-unified-agent.jar'

- task: PowerShell@2
  displayName: 'Perform EUA scan'
  inputs:
    targetType: 'inline'
    script: |
      java -jar wss-unified-agent.jar -appPath aspnetcore-realworld-example-app\src\Conduit\bin\Debug\netcoreapp3.1\Conduit.dll -d .
